---
fixtures:
  repositories:
    #systemd: https://github.com/voxpupuli/puppet-systemd.git
      #stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    archive: https://github.com/voxpupuli/puppet-archive.git
      #concat: https://github.com/puppetlabs/puppetlabs-concat.git
